language: generic

git:
  depth: 1

dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_install:
  - wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
  - sh cmake-3.12.4-Linux-x86_64.sh --prefix=. --exclude-subdir
  - . travis/install-cuda-xenial.sh
  - sudo apt-get -qq update
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y libglu1-mesa-dev
  - sudo apt-get install -y uuid-dev
  - sudo apt-get install -y libunwind8-dev
  - sudo apt-get install -y libxrandr-dev
  - sudo apt-get install -y libxinerama-dev
  - sudo apt-get install -y libxcursor-dev
  - sudo apt-get install -y libxi-dev
  - sudo apt-get install -y libcgal-qt5-dev
  - sudo apt-get install -y libcgal-dev
  - mkdir build && cd build
  - ../bin/cmake .. -DCMAKE_CXX_FLAGS=-Wno-deprecated-declarations -DSUPPRESS_CUDA_WARNINGS=TRUE

install:
  - make install
