language: generic

git:
  depth: 1

dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
            - cuda-drivers
            - cuda-cudart-dev-10-1
            - cuda-compiler-10-1
            - cuda-cufft-dev-10-1
            - cuda-cusparse-dev-10-1
            - cuda-cusolver-dev-10-1
            - libcublas-dev
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
            - cuda-drivers
            - cuda-cudart-dev-10-1
            - cuda-compiler-10-1
            - cuda-cufft-dev-10-1
            - cuda-cusparse-dev-10-1
            - cuda-cusolver-dev-10-1
            - libcublas-dev
      env:
        - CC=gcc-9
        - CXX=g++-9

before_install:
  - . travis/install-cuda-xenial.sh
  - mkdir build && cd build
  - cmake ../ -DCMAKE_CXX_FLAGS=-Wno-deprecated-declarations -DENABLE_CUDA=ON -DSUPPRESS_CUDA_WARNINGS=TRUE -DBUILD_PROTEIN_CUDA_PLUGIN=ON

install:
  - make install
