language: cpp

git:
  depth: 3

dist: focal

jobs:
  include:
    - name: "gcc-9 (Make)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - GENERATOR="Unix Makefiles"
    - name: "gcc-9 (Ninja)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - g++-9
            - ninja-build
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - GENERATOR=Ninja
    - name: "clang-10 (Make)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - clang-10
            #- libiomp-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=clang-10
        - CXX=clang++-10
        - GENERATOR="Unix Makefiles"

before_install:
  - . .travis/travis-retry.sh
  - . .travis/install-cuda.sh

script:
  - mkdir build && cd build
    # Use absolute path to cmake, otherwise we will use the travis version (3.12, too old).
  - /usr/bin/cmake .. -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-w -DENABLE_CUDA=ON -DSUPPRESS_CUDA_WARNINGS=TRUE -DBUILD_ADIOS_PLUGIN_PLUGIN=ON -DBUILD_PROTEIN_CUDA_PLUGIN=ON -DBUILD_MEGAMOL101_PLUGIN=ON -DBUILD_REMOTE_PLUGIN=ON
  - /usr/bin/cmake --build . --target install
