shallow_clone: true
clone_depth: 1

branches:
  only:
  - master

environment:
  matrix:
    - platform: x64
      configuration: Release
      image: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      CMAKE_CONFIG: Release
      VSVER: vs141
    - platform: x64
      configuration: Debug
      image: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      CMAKE_CONFIG: Debug
      VSVER: vs141
    - platform: x64
      configuration: RelWithDebInfo
      image: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      CMAKE_CONFIG: RelWithDebInfo
      VSVER: vs141
    - platform: x64
      configuration: Release
      image: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_CONFIG: Release
      VSVER: vs142
    - platform: x64
      configuration: Debug
      image: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_CONFIG: Debug
      VSVER: vs142
    - platform: x64
      configuration: RelWithDebInfo
      image: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_CONFIG: RelWithDebInfo
      VSVER: vs142

matrix:
  fast_finish: true

before_build:
  - mkdir build
  - mkdir stage
  - cd build
  - cmake .. -G"%CMAKE_GENERATOR%" -A"x64" -DCMAKE_BUILD_TYPE=%CMAKE_CONFIG% -DCMAKE_INSTALL_PREFIX=c:\projects\megamol\stage\

build:
  parallel: true

build_script:
  - cmake --build . --target install --config %CMAKE_CONFIG%

after_build:
  - cd c:\projects\megamol\stage\
  - 7z a -y -bd megamol.zip
  - ps: Push-AppveyorArtifact "megamol.zip" -Filename "megamol-${env:VSVER}-${env:Platform}-${env:Configuration}.zip"
