shallow_clone: true

clone_depth: 1

environment:
  matrix:
    - platform: x64
      configuration: Release
      os: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      CMAKE_CONFIG: Release
      VSVER: vs140
    - platform: x64
      configuration: Debug
      os: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      CMAKE_CONFIG: Debug
      VSVER: vs140
    - platform: x64
      configuration: Release
      os: Visual Studio 2013
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      CMAKE_CONFIG: Release
      VSVER: vs120
    - platform: x64
      configuration: Debug
      os: Visual Studio 2013
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      CMAKE_CONFIG: Debug
      VSVER: vs120

matrix:
  fast_finish: true

before_build:
  - mkdir build
  - mkdir stage
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=c:\projects\megamol\stage\

build:
  parallel: true

build_script:
  - cmake --build . --target install --config %CMAKE_CONFIG%

after_build:
  - cd c:\projects\megamol\stage\
  - 7z a -y -bd megamol.zip
- ps: Push-AppveyorArtifact "megamol.zip" -Filename "megamol-${env:VSVER}-${env:Platform}-${env:Configuration}.zip"